### ISSUE TITLE
How to compile, install, and launch NOVA

### ISSUE THREAD

**Issue by bronzeMe** [udosteinberg/NOVA#10]
We couldn’t find instructions on how to install and launch NOVA in the [doc](https://github.com/udosteinberg/NOVA/tree/release/doc). Could you provide more details about how to compile, install, and launch NOVA? Thank you

We try boot it as the following, but failed![image](https://github.com/user-attachments/assets/c2cac0e9-638f-4dde-a3b6-6c2d47cefc05)

**Comment by udosteinberg** [comment]
Looks like you already managed to compile and install NOVA.

The general steps would be:
```
git clone https://github.com/udosteinberg/NOVA
cd NOVA
make -j install INS_DIR=/boot
```
For booting, you need a multiboot-compliant bootloader, such as GRUB2, where you can create an entry like the following (make sure to adjust the paths as needed):
```
menuentry 'NOVA' {
        insmod part_gpt
        insmod multiboot2
        echo 'Loading NOVA Microhypervisor ...'
        multiboot2 /boot/x86_64-nova
}
```
NOVA does not print anything on the screen, it logs everything to the UART. So you need to connect to a physical COM port (if your machine has one) or use AMT SOL (with amtterm, meshcommander or similar).

**Comment by bronzeMe** [comment]
We try to boot NOVA using QEMU, i.e., using kvm nested virtualizaition , but also failed
Steps as the following:

1. start vm
```bash
qemu-system-x86_64 \
-enable-kvm \
-m 4096 \
-smp 4 \
-drive file=ubuntu-server.qcow2,format=qcow2,if=virtio \
-cpu host \
-nographic \
-serial stdio \
-monitor telnet:127.0.0.1:5555,server,nowait \
-device virtio-net,netdev=user.0 \
-netdev user,id=user.0,hostfwd=tcp::2222-:22 \
-drive if=pflash,format=raw,readonly,file=/usr/share/OVMF/OVMF_CODE.fd \
-drive if=pflash,format=raw,file=/home/test/OVMF_VARS.fd
```

2. compile NOVA and install it
```bash
make -j install INS_DIR=/boot
# create menu
# /etc/grub.d/40_custom
menuentry 'NOVA' {
        insmod part_gpt
        insmod multiboot2
        echo 'Loading NOVA Microhypervisor ...'
        multiboot2 /boot/x86_64-nova
        echo 'Setting up serial console...'
        terminal_output serial console
}
# edit /etc/default/grub
GRUB_TERMINAL="serial console"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
GRUB_TIMEOUT_STYLE=menu
GRUB_TIMEOUT=10
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,115200n8"
GRUB_CMDLINE_LINUX=""

```
3.  boot the NOVA menu via GRUB ,but it stuck
![image](https://github.com/user-attachments/assets/5fba85af-0e98-463b-935e-bb78efbb5714)

![image](https://github.com/user-attachments/assets/d6b8d144-9628-4346-95a9-bebc031d1b30)

**Comment by udosteinberg** [comment]
Do you see output when you simply type `make run` in the NOVA directory?

**Comment by bronzeMe** [comment]
```bash
➜  NOVA git:(release) ✗ make run
qemu-system-x86_64  -m 512 -smp 4 -no-reboot -display none -serial mon:stdio -M q35 -append serial -kernel build-x86_64/x86_64-nova.elf

NOVA Microhypervisor #e7fc14d-0x7 (x86_64): Sep  8 2024 14:23:13 [gcc 12.3.0]

[ -1] RSDT: 0x1ffe220e OEM:BOCHS  TBL:BXPCRSDT REV: 1 LEN:      52 (ok)
[ -1] FACP: 0x1ffe2016 OEM:BOCHS  TBL:BXPCFACP REV: 3 LEN:     244 (ok)
[ -1] APIC: 0x1ffe210a OEM:BOCHS  TBL:BXPCAPIC REV: 1 LEN:     144 (ok)
[ -1] HPET: 0x1ffe219a OEM:BOCHS  TBL:BXPCHPET REV: 1 LEN:      56 (ok)
[ -1] MCFG: 0x1ffe21d2 OEM:BOCHS  TBL:BXPCMCFG REV: 1 LEN:      60 (ok)
[ -1] ACPI: Version 3.0 Profile 0 Features 0x84a5 Boot 0x0
[ -1] FACS: Hardware 0x0 Flags 0x0 Wake 0x0/0x0
[ -1] PCIE: 0xb0000000 Segment 0x0000 Bus 0x00-0xff
[ -1] PCIE: 8086:29c0 06-00-00 D0                    0000:00:00.0
[ -1] PCIE: 1234:1111 03-00-00 D0                    0000:00:01.0
[ -1] PCIE: 8086:10d3 02-00-00 D0 PCIE PMI           0000:00:02.0
[ -1] PCIE: 8086:2918 06-01-00 D0                    0000:00:1f.0
[ -1] PCIE: 8086:2922 01-06-01 D0                    0000:00:1f.2
[ -1] PCIE: 8086:2930 0c-05-00 D0                    0000:00:1f.3
[ -1] HPET: 0xfed00000
[ -1] APIC: I/O:0x00 VER:0x20 GSI:0x00-0x17 (0000:00:00.0)
[  0] FREQ: 2819659200 Hz (measured) Ratio:3
[  0] APIC: LOC:0x00 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
[  0] MCHK: 0/10 banks
[  0] VIRT: SVM:0x1 NPT:0
[  0] CORE: 00:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
[  1] APIC: LOC:0x01 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
[  1] MCHK: 0/10 banks
[  1] VIRT: SVM:0x1 NPT:0
[  1] CORE: 01:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
[  3] APIC: LOC:0x03 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
[  3] MCHK: 0/10 banks
[  3] VIRT: SVM:0x1 NPT:0
[  3] CORE: 03:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
[  2] APIC: LOC:0x02 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
[  2] MCHK: 0/10 banks
[  2] VIRT: SVM:0x1 NPT:0
[  2] CORE: 02:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
[  0] TIME: 90ms 0ms/0ms
[  0] ROOT: No image provided
```

```bash
root@yi:/NOVA/build-x86_64# ld --version
GNU ld (GNU Binutils for Ubuntu) 2.38
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
root@yi:/NOVA/build-x86_64# make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@yi:/NOVA/build-x86_64# gcc --version
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by udosteinberg** [comment]
So NOVA works. When you boot it natively, how do you obtain the UART output?

**Comment by bronzeMe** [comment]
> ```shell
> ➜  NOVA git:(release) ✗ make run
> qemu-system-x86_64  -m 512 -smp 4 -no-reboot -display none -serial mon:stdio -M q35 -append serial -kernel build-x86_64/x86_64-nova.elf
> 
> NOVA Microhypervisor #e7fc14d-0x7 (x86_64): Sep  8 2024 14:23:13 [gcc 12.3.0]
> 
> [ -1] RSDT: 0x1ffe220e OEM:BOCHS  TBL:BXPCRSDT REV: 1 LEN:      52 (ok)
> [ -1] FACP: 0x1ffe2016 OEM:BOCHS  TBL:BXPCFACP REV: 3 LEN:     244 (ok)
> [ -1] APIC: 0x1ffe210a OEM:BOCHS  TBL:BXPCAPIC REV: 1 LEN:     144 (ok)
> [ -1] HPET: 0x1ffe219a OEM:BOCHS  TBL:BXPCHPET REV: 1 LEN:      56 (ok)
> [ -1] MCFG: 0x1ffe21d2 OEM:BOCHS  TBL:BXPCMCFG REV: 1 LEN:      60 (ok)
> [ -1] ACPI: Version 3.0 Profile 0 Features 0x84a5 Boot 0x0
> [ -1] FACS: Hardware 0x0 Flags 0x0 Wake 0x0/0x0
> [ -1] PCIE: 0xb0000000 Segment 0x0000 Bus 0x00-0xff
> [ -1] PCIE: 8086:29c0 06-00-00 D0                    0000:00:00.0
> [ -1] PCIE: 1234:1111 03-00-00 D0                    0000:00:01.0
> [ -1] PCIE: 8086:10d3 02-00-00 D0 PCIE PMI           0000:00:02.0
> [ -1] PCIE: 8086:2918 06-01-00 D0                    0000:00:1f.0
> [ -1] PCIE: 8086:2922 01-06-01 D0                    0000:00:1f.2
> [ -1] PCIE: 8086:2930 0c-05-00 D0                    0000:00:1f.3
> [ -1] HPET: 0xfed00000
> [ -1] APIC: I/O:0x00 VER:0x20 GSI:0x00-0x17 (0000:00:00.0)
> [  0] FREQ: 2819659200 Hz (measured) Ratio:3
> [  0] APIC: LOC:0x00 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
> [  0] MCHK: 0/10 banks
> [  0] VIRT: SVM:0x1 NPT:0
> [  0] CORE: 00:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
> [  1] APIC: LOC:0x01 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
> [  1] MCHK: 0/10 banks
> [  1] VIRT: SVM:0x1 NPT:0
> [  1] CORE: 01:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
> [  3] APIC: LOC:0x03 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
> [  3] MCHK: 0/10 banks
> [  3] VIRT: SVM:0x1 NPT:0
> [  3] CORE: 03:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
> [  2] APIC: LOC:0x02 VER:0x14 SUP:0 LVT:0x5 (xAPIC OS Mode)
> [  2] MCHK: 0/10 banks
> [  2] VIRT: SVM:0x1 NPT:0
> [  2] CORE: 02:00.0 6:6:3:0 [0] QEMU Virtual CPU version 2.5+
> [  0] TIME: 90ms 0ms/0ms
> [  0] ROOT: No image provided
> ```
It threw a 'ROOT: No image provided' error. How do we boot NOVA using only QEMU?

**Comment by udosteinberg** [comment]
> It threw a `ROOT: No image provided` error.

That is not an error. That is an informative message stating that NOVA wanted to load a multiboot module for the RootPD, but none was provided.

> How do we boot NOVA using only QEMU?

As you did with `make run` or using a similar QEMU invocation.

**Comment by bronzeMe** [comment]
> > It threw a `ROOT: No image provided` error.
> 
> That is not an error. That is an informative message stating that NOVA wanted to load a multiboot module for the RootPD, but none was provided.
> 
We booted NOVA on a physical server, and it still showed "ROOT: No image provided," just as it did when booting via QEMU.
We add a custom menu 
```bash
menuentry 'NOVA' {
        insmod part_gpt
        insmod multiboot2
        echo 'Loading NOVA Microhypervisor ...'
        multiboot2 /boot/x86_64-nova
}
```
<img width="462" alt="image" src="https://github.com/user-attachments/assets/902e1165-ebb8-406f-b997-7392576bc7dc">

Could you please provide some suggestions? Thanks a lot.

**Comment by udosteinberg** [comment]
You will need a user-mode environment that runs on top of NOVA. NOVA itself is just the kernel/hypervisor portion of the software stack and thus does not include one in this repository.  Thus, as far as NOVA is concerned, it has booted successfully as far as possible and now all cores are in the idle loop.

What user-mode environment were you planning to run on top?

**Comment by bronzeMe** [comment]
> NOVA itself is just the kernel/hypervisor portion of the software stack and thus does not include one in this repository

 NOVA has other corresponding software stacks, but they are not open source?  

 Additionally, for KVM or XEN, there is usually a Host or Dom0 to provide user interaction and create VMs. For NOVA, what is its interaction method? For example, if I want NOVA to start an Ubuntu 20.04 VM, how should I proceed? Thanks

**Comment by udosteinberg** [comment]
There are various open-source stacks that run on top of older versions of NOVA:
* https://github.com/TUD-OS/NUL
* https://github.com/TUD-OS/NRE
* https://github.com/genodelabs/genode
You could run any of these on an older version of NOVA or port them to the latest version of NOVA.

Alternatively, you could contact support@bluerock.io for licensing options for NOVA's current user-mode environment.
