### ISSUE TITLE
Building newer sources for x86_64

### ISSUE THREAD

**Issue by lonnietc** [udosteinberg/NOVA#3]
Will these sources also build the latest NOVA for x86_64 or have they been optimized for ARM?
Thanks

**Comment by lonnietc** [comment]
Any update on this?

**Comment by blitz** [comment]
That's probably a question for @udosteinberg.

**Comment by lonnietc** [comment]
Thanks,  I'm able to to compile the "arm" branch with x86_64 settings, but still have the problem even the latest version of Bender although I do not have any ideas on other loaders that might work instead. I like the idea of Bender since it worked in the past with the Userland Demos (albeit 32-bit versions).

I have been able to compile and use the latest Bender as well as the Userland NUL (https://os.inf.tu-dresden.de/nul/) in particular the 0.3 Demo version on that page which all compiles file, but I am still stuck with using the original NOVA Hypervisor to make it work. It seems that all of the different versions of NOVA hypervisor that I have compiled and tried, both 32-bit and 64-bit, just do not work and I get errors when booting.

I am still trying to just get a basic NOVA Hypervisor compiled (preferably x86_64) with the latest Bender (https://github.com/blitz/bender) that supports 64-bit ELF's, along with the NUL 0.3 core (https://os.inf.tu-dresden.de/nul/nova-userland-0.3.tar.bz2) to all work together so that I have the simplest baseline to work with as a starting point, but things do not seem to be as simple as just compiling up the sources as all of the developers have gone different directions and it is vary hard to get just the basic components to work together just so that I can replicate the the "Demo CD" (https://os.inf.tu-dresden.de/nul/NOVA-0.3.iso.bz2) from sources.

At this stage, I have not had success even it getting a complete 32-bit set of components to work together even though each set of sources (NOVA, Bender old-sources, and NUL 0.3) compiles cleanly, although a 64-bit version of NOVA is preferable.

It all may have something to do with the fact that we now have gcc 9 and gcc 7, verses what was used a few years back to make the Demo CD

I do not know, how to proceed best, but am determined to figure out a way and hopefully can get some help from the developers to just get this baseline setup from which I can build from this point forward.

Any help (especially to get the x86_64 version of NOVA working with Bender and NUL 0.3) would be sincerely appreciated.
Thanks in advance

**Comment by dnimeerf** [comment]
I would love to work toward the end of a 32 bit commutative version. This
way it's modular, and scalable when new choosers become avail due to the
end of Moore's law. This also sets up well for distributed systems.

**Comment by lonnietc** [comment]
I would just like to get a basic NOVA + NUL to compile (which I can do for both 32-bit and 64-bit), but when you put them together the system just does not play nicely together and crashes out.

I have even replaced the old Bender loaded that is supposed to work with 32-bit ELF's with the newer one that also is supposed to work with 64-bit ELF's but the results are the same.

1. Original:  pre-compiled 32-bit NOVA with newly compiled NUL --- boots

2. Fresh compiled NOVA 32-bit, 32-bit Bender (original), NUL (original) --- crashes

3. Original NOVA 32-bit (taken from demo), Bender (new), NUL (original) --- boots

4. Fresh compiled NOVA 64-bit, 64-bit Bender (new), NUL (original) --- crashes

Basically, no matter how I compile NOVA, it will just not work wit the other parts even if they are the originals that I have taken from the DEMO 0.3 DC which was what I was trying to replicate in the first step.

My second step was going to be to replace the 32-bit NOVA and old Bender with the 64-bit NOVA and new Bender and use the original NUL files just to get things to work, but I seem to be no where near that second step being that I cannot get past the first step right now.

Am still working on it, but still a long ways to go as I know that the developers have moved on to other things and this is not a high priority to them any more, from what I can see.

None the less, NOVA is an awesome microhypervisor and I think that it holds a HUGE potential, so I am going to press on to get it working if I can.
Cheers

**Comment by blitz** [comment]
@lonnietc When you say "freshly compiled NOVA", do you mean the current sources? This is not going to work, because the API to the hypervisor has changed. If you want to compile NOVA from source, you need to take a version from the same timeframe as the userspace.T here is also no way to get 32-bit NUL working on a 64-bit hypervisor, because 64-bit NOVA does not support running 32-bit userspace binaries (except in VMs). Hope that helps a bit.

**Comment by lonnietc** [comment]
@blitz Yea,I was thinking about that and you hit things right on the head.

Seems like to get a full 64-bit NOVA and 64-bit NUL combination compiling both from the sources and using the your new Bender will take a significant amount of work and time.  

Well, that's the goal that I have in being able to use NOVA/NUL as the base to build from and will have to see what can be done. If you get an free time and are interested in helping me to get it working then I would greatly appreciate your help since you have a good feel for things, but also understand that you are pretty busy as well.

Cheers and take care, my friend.

**Comment by Nils-TUD** [comment]
You might also want to take a look at [NRE](https://github.com/TUD-OS/NRE), which is the successor of NUL. It's also quite dated and I haven't tried it in recent years, but it might work more seamlessly than NUL.

**Comment by chelmuth** [comment]
Throwing hats in the ring? [Genode](https://github.com/genodelabs/genode) is anything but dated and uses a recent version of NOVA. But, I've the feeling @lonnietc knows about this.

**Comment by lonnietc** [comment]
Hi All,

Hope that everyone is going well today.

@Nils-TUD Thanks, I actually tried NRE but had some troubles with the build so I took a step back and just re-compiled NUL from scratch which worked out nicely.  I was going to try to get basic 64-bit versions of NOVA & NUL built and working to replicate the DEMO 0.3 CD but on a 64-bit basis and then take the next step to swap out NUL for NRE perhaps or some other simple direction like looking into Bhyve or Xhyve as a single instance VMM, but had not made a decision on that until I could replicate at least the basic DEMO 0.3 setup as a first step.

@chelmuth Genode is a very good set of libraries and I looked in that direction as a first step since it allowed for NOVA as the hypervisor (I also played with the idea of MUEN, but my hardware is AMD and while MUEN only supports Intel and there are no plans for AMD support from what I understand).   Being that I considered Genode + VirtualBox (as the VMM) running under Sculpt OS but found that it was very cumbersome to work with together and Genode just seems to be too generalized for what I simple want which is a ultra-thin extremely small footprint  hypervisor (NOVA 64-bit) and a viable single-instance VMM to run some ISO's inside.

Everything is a bit dated, but I firmly believe that NOVA & a good single-instance VMM (Bhyve or Xhyve perhaps) running RAM-Based while just using the local/remote/NAS HD mappings for APP VM's would make an AWESOME Type-1 hypervisor that could even compete (in time) with the likes of Xen (XCP-ng), and others.

The goal of it all was to move towards a paradigm shift such that this new Type-1 hypervisor (NOVA+VMM) could run Unikernel APPS from different platforms (Linux, Windows, etc..) or that it could easily run complete development environments in VM's and the user would interact with the VM's via an RDP client since it is extremely powerful and offers channels for mapping resources. 

Ultimately this would bring about a new highly distributed OS in which users could share/utilize resources from across many distributed physical systems while connected to their VM's that may be located locally or remotely, but as they are using an RDP client, even on the local system to connect to local VM's the whole system appears as a homogeneous OS similar to what they have been using now, but also having much more security in that each Unikernel Application is in its own VM.  

This approach also helps to mitigate data hijacking since user data is "mapped" into any VM that needs it and not into others thus enforcing strict User-Data and Application isolation and separation. 

The whole idea is that of JeOS (Just Enough OS) and application independence with a Hypervisor at its core and different platform applications running with Unikernels in ultra-secure single-instance VM's that only map in the user data that is needed specifically for that application.  Should an Application get hacked then that Application VM instance is turned off and the hack is minimized since the attach surface is minimal and the attacker does not have access to the rest of the system.

Of course there are many other security benefits as well as virtually eliminating the whole IT push-patch problem in that when a new Application comes from the software vendor or developer then it is as a single type of OVA that can be imported into the user's APP storage space that holds the pristine OVA and on the next use to the application, the VMM just starts up an instance of the OVA that was imported and not affecting the original APP.  Then, IT upgrading is extremely easy and no user system patching is required.  Other benefits to this whole idea can be seen as well.

As much later advancement perhaps, I thought about maybe having Muen to provide hardware separation along with NOVA on selected configurations and single-instance VMM's, but that was just playing with some ideas, but we all go to have dreams even if they are a huge challenge to achieve them. 

I firmly believe that this project can create a new paradigm that can help thousands of users and businesses to have more secure and flexible computing at their fingertips, and I will do my best to make it happen. Of course, not everyone agrees with this approach, and that is fine since the goal is to ultimately make a system that will help people and enhance computer security in the Cloud based age of computing and there are different ways to achieve this objective.

But for the basis of this project, there needs to be a an ultra small ram-based hypervisor and the best that I have seen after MUCH searching, at least for now, is NOVA directly, a simple GUI, and VMM.

Sorry for the long reply, but it all starts with NOVA and reasonable VMM.
Cheers
Lonnie

**Comment by lonnietc** [comment]
@chelmuth  I actually really do like the idea of Genode on top of NOVA running as the MicroHypervisor and tried very hard to use the SculptOS to just add VirtualBox and nothing more to see if I could get a demo of this combination to work, but never could get it completely setup or working correctly.

After a lot of time trying, I decided that it might not be the most fruitful path forward since it was taking so long just to get something working to test as a demo that is supposed to already be within the SculptOS capabilities.

To that end, I wanted a ultra-small footprint combination of:

NOVA with Genode and VirtualBox on top as the only application so that I could generate an ISO that would be RAM-based that could boot a couple of OS's in VM's to see how it worked.

I even looked into possibly contracting the Genode folks to help, but being a self-funded project, the pricing was far more than I could afford, especially for a demo.

The alternative that I really like (due to the KISS principle) is simple NOVA with a GUI and able to run a VMM that can boot some OS instances like in the dated Demo 0.3 and although I could compile the components independently, it seems that trying to get things to work together is the problem even on the x86_32 base which I wanted to test and then work toward a complete x86_64 based NOVA and NRE (or NUL) applications, but this too will require a huge amount of re-development.

I still firmly believe that NOVA is the BEST possible solution for my project objectives, but it will take a considerable amount development and time to make it happen since most of the originally NOVA & NRE/NUL developers have moved on to other projects over the years.

Anyway, it remains a dream and goal that I will continue to slowly work on when possible.

Thanks again all and have a great day
