### ISSUE TITLE
vTLB addressing limit exceeded problem

### ISSUE THREAD

**Issue by lonnietc** [udosteinberg/NOVA#4]
Hello,

I have a question related to NOVA and tried to email the hypervisor.org email address but have not heard back so I fear that it was not received.

I am working with NRE now and am porting over the musl Clib so that I can try to work towards porting the (FreeBSD) bhyve VMM over to the platform instead of Vancouver (Seoul) as it is more complete and industry standard while being lightweight (about 500 KB).

Testing some stuff on the NRE platform which is currently using QEMU to run NOVA+NRE and some apps to include Vancouver for TinyCore linux, I made a simple adjustment to the boot parameters for QEMU to increase the memory RAM from 2048 MB to 8192 MB as I have 18 GB on this test system.

To my surprise, the vmmng code which usually has no problems at all when I have the QEMU ram set at 2048, but when setting the RAM higher, I get a vTLB error which seems to be coming from NOVA not being able to access the upper address space.

Killed EC:0xffffffff82094a60 SC:0xffffffff82038e40 V:0xfc CR0:0x11 CR3:0x0 CR4:0x0 (vTLB addressing limit exceeded)

this seems to suggest, although I could be wrong, that the version of NOVA that I am running (x86_64 hardware AMD and Intel test machines):

https://github.com/TUD-OS/NOVA/tree/1ab3e588b8808146783772288f34905600dd21c2

is acting like it is compiled for 32-bit hardware but is actually compiled for 64-bit hardware in seeing some upper problem with the RAM threshold.

I'm just not clear as to what is happening and how to resolve this.  

Does this mean that I should work on upgrading the NOVA code from the current (above) to your latest NOVA:

https://github.com/udosteinberg/NOVA

so that I can take advantage of much larger address space, or is there something else happening that you may be aware of for NOVA?

Any information or guidance that you could provide would be greatly appreciated.
Thanks again and have a great day.

**Comment by chelmuth** [comment]
Have you tried to remove the `vtlb` command-line parameter from the hypervisor boot entry? I guess the vTLB code is not able to handle that much RAM as it's only required on CPUs without nested paging (EPT/NPT).

**Comment by lonnietc** [comment]
Hello,

Thanks for your reply on this question.   There is no vtlb command-line parameter from as far as I can tell.

 ./b qemu boot/vmmtest

For the NRE framework, it uses a script "./b" that ensures that SCons is updated for the build and then calls "novaboot" which has some for the "boot/vmmtest"

---   boot/vmmtest file------------------------------
#!tools/novaboot

sh command removed because it make the github post look bad with the special characters

QEMU_FLAGS=-m 8192 -smp 4 -netdev user,id=mynet0 -device ne2k_pci,netdev=mynet0
HYPERVISOR_PARAMS=spinner serial
bin/apps/root
bin/apps/acpi provides=acpi
bin/apps/keyboard provides=keyboard
bin/apps/reboot provides=reboot
bin/apps/pcicfg provides=pcicfg
bin/apps/timer provides=timer
bin/apps/console provides=console
bin/apps/network provides=network
bin/apps/sysinfo
bin/apps/vmmng mods=all lastmod
bin/apps/vancouver
bin/apps/cycleburner
bin/apps/guest_munich
dist/imgs/bzImage-3.1.0-32
dist/imgs/initrd-js.lzma
dist/imgs/tinycore-vmlinuz
dist/imgs/tinycore-core.gz
cycleburner.vmconfig <<EOF
rom://bin/apps/cycleburner
EOF
tinycore-linux.vmconfig <<EOF
rom://bin/apps/vancouver m:128 ncpu:1 PC_PS2 intel82576vf
rom://bin/apps/guest_munich
rom://dist/imgs/tinycore-vmlinuz noapic console=ttyS0
rom://dist/imgs/tinycore-core.gz
EOF
------------------------------

The vmmtest file is exactly the same that I use when testing the everything but changing the QEMU RAM from 2048 to 8192 
 memory.

I have also checked in the "novaboot" program to see if something is being added but cannot find anything there as well.

**Comment by Nils-TUD** [comment]
Christian was talking about the `HYPERVISOR_PARAMS`, which indeed contains no `vtlb` in your boot script. But note that with VMX, the vTLB is used implicitly if nested paging is not available, which I think is the case with QEMU. So, as long as your production platform is not QEMU or an old real machine without nested paging, it should be fine.

**Comment by lonnietc** [comment]
That's a good point about it possibly being QEMU as that had not occurred to me, and as you already know, I am just using QEMU for development and testing so, in fact, all of this might be a moot point on real hardware.

Truly appreciate the feedback and comments from everyone.

**Comment by udosteinberg** [comment]
vTLB functionality has been deprecated and removed from NOVA a while ago due to the fact that EPT has been around in hardware since 2008.
